// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/de/messages.json"
    | "/_locales/en/messages.json"
    | "/assets/icons/icon128.png"
    | "/assets/icons/icon128.psd"
    | "/assets/icons/icon16.png"
    | "/assets/icons/icon48.png"
    | "/background.js"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
